let modeloJson = [
    {
      id: 1,
      name: 'Camiseta Black Sabbath',
      img: 'img/1.png',
      price: 20.19,
      sizes: ['malha', 'algodão', 'dry'],
      description: 'Blusa Estampa com Manga Banda Black Sabbath',
    },
    {
      id: 2,
      name: 'Camiseta The Beatles 1969',
      img: 'img/2.png',
      price: 18.0,
      sizes: ['algodão', 'malha', 'dry'],
      description: 'Blusa Estampa The Beatles no seu último show ',
    },
    {
      id: 3,
      name: 'Camiseta Preta Nirvana',
      img: 'img/3.png',
      price: 17.45,
      sizes: ['dry', 'malha', 'algodão'],
      description: 'Blusa Preta Nirvana Estampa Album In Utero ',
    },
    {
      id: 4,
      name: 'Camiseta The Beatles 1963',
      img: 'img/4.png',
      price: 19.77,
      sizes: ['algodão', 'malha', 'dry'],
      description: 'Camisa Branca Estampa Último Show Beatles na Cavern Club',
    },
    {
      id: 5,
      name: 'Camiseta Preta Pink Floyd',
      img: 'img/5.png',
      price: 21.43,
      sizes: ['malha', 'algodão', 'dry'],
      description: 'Blusa Estampa Banda Pink Floyd',
    },
    {
      id: 6,
      name: 'Camiseta Preta Queen',
      img: 'img/6.png',
      price: 18.55,
      sizes: ['malha', 'dry', 'algodão'],
      description: 'Blusa Preta Com Manga Banda Queen',
    },
    {
      id: 7,
      name: 'Camiseta Fleetwood Mac',
      img: 'img/7.png',
      price: 22.36,
      sizes: ['malha', 'dry', 'dry'],
      description: 'Blusa Preta Com Manga Banda Fleetwood Mac',
    },
  ];