let modeloJson = [
    {
      id: 1,
      name: 'Black Sabbath',
      img: 'img/1.png',
      price: 20.19,
      sizes: ['malha', 'algodão', 'dry'],
      description: 'Camisa preta com manga e estampa Black Sabbath',
    },
    {
      id: 2,
      name: 'The Beatles 1969',
      img: 'img/2.png',
      price: 18.0,
      sizes: ['algodão', 'malha', 'dry'],
      description: 'Camisa bege com manga e estampa The Beatles',
    },
    {
      id: 3,
      name: 'Nirvana - In Utero',
      img: 'img/3.png',
      price: 17.45,
      sizes: ['dry', 'malha', 'algodão'],
      description: 'Blusa preta com manga e estampa Nirvana',
    },
    {
      id: 4,
      name: 'The Beatles 1963',
      img: 'img/4.png',
      price: 19.77,
      sizes: ['algodão', 'malha', 'dry'],
      description: 'Camisa branca com manga e estampa',
    },
    {
      id: 5,
      name: 'Pink Floyd',
      img: 'img/5.png',
      price: 21.43,
      sizes: ['malha', 'algodão', 'dry'],
      description: 'Camisa preta com manga e estampa Pink Floyd',
    },
    {
      id: 6,
      name: 'Queen',
      img: 'img/6.png',
      price: 18.55,
      sizes: ['malha', 'dry', 'algodão'],
      description: 'Camisa preta com manga e estampa Queen',
    },
    {
      id: 7,
      name: 'Fleetwood Mac',
      img: 'img/7.png',
      price: 22.36,
      sizes: ['malha', 'dry', 'dry'],
      description: 'Camisa preta com manga e estampa Fleetwood Mac',
    },
  ];